categories:
  - name: images
    extensions:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
  - name: movies
    extensions:
      - mp4
      - mpeg
      - mpg
      - mov
      - avi
      - mkv
  - name: documents
    extensions:
      - txt
      - md
      - pdf
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - rtf
      - log
default_category: others
date_patterns:
  # yyyy-mm-dd... e.g., 2024-01-31_photo.jpg
  - (?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})
  # IMG_yyyymmdd_... e.g., IMG_20240131_123456.jpg
  - IMG_(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_
